server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: conference
          uri: lb://CONFERENCE-SERVICE
          predicates:
            - Path=/api/conferences/**
        - id: keynote
          uri: lb://KEYNOTE-SERVICE
          predicates:
            - Path=/api/keynotes/**
